import { Plant } from "@/types";

export const plantsData : Plant[] = [
  {
    id: 101,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 616,
    discount: 20,
    reviews: 385,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Indirect sunlight, moist soil.",
    height: "10 inches",
    weight: "300g",
    size: "Small"
  },
  {
    id: 102,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 85,
    discount: 5,
    reviews: 295,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water once a week, keep in sunlight.",
    height: "8 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 103,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 418,
    discount: 10,
    reviews: 239,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Water once a week, keep in sunlight.",
    height: "15 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 104,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 982,
    discount: 15,
    reviews: 472,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Indirect sunlight, moist soil.",
    height: "10 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 105,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 638,
    discount: 10,
    reviews: 97,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Moist soil, low light.",
    height: "20 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 106,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 105,
    discount: 20,
    reviews: 67,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Indirect sunlight, moist soil.",
    height: "12 inches",
    weight: "750g",
    size: "Small"
  },
  {
    id: 107,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 716,
    discount: 20,
    reviews: 136,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 108,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 617,
    discount: 5,
    reviews: 114,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "8 inches",
    weight: "300g",
    size: "Small"
  },
  {
    id: 109,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 554,
    discount: 0,
    reviews: 466,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Moist soil, low light.",
    height: "12 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 110,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 95,
    discount: 15,
    reviews: 459,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Indirect sunlight, moist soil.",
    height: "12 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 111,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 253,
    discount: 15,
    reviews: 482,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "15 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 112,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 776,
    discount: 5,
    reviews: 252,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water once a week, keep in sunlight.",
    height: "20 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 113,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 111,
    discount: 20,
    reviews: 478,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 114,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 727,
    discount: 0,
    reviews: 453,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 115,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 845,
    discount: 0,
    reviews: 336,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "750g",
    size: "Small"
  },
  {
    id: 116,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 167,
    discount: 0,
    reviews: 312,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "15 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 117,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 850,
    discount: 5,
    reviews: 321,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 118,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 818,
    discount: 5,
    reviews: 424,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "15 inches",
    weight: "1kg",
    size: "Large"
  },
  {
    id: 119,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 300,
    discount: 5,
    reviews: 71,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "15 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 120,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 679,
    discount: 15,
    reviews: 314,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 121,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 585,
    discount: 10,
    reviews: 273,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "20 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 122,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 388,
    discount: 0,
    reviews: 123,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Indirect sunlight, moist soil.",
    height: "15 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 123,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 346,
    discount: 5,
    reviews: 84,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water once a week, keep in sunlight.",
    height: "8 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 124,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 341,
    discount: 15,
    reviews: 101,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Full sunlight, moderate watering.",
    height: "20 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 125,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 448,
    discount: 0,
    reviews: 92,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 126,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 600,
    discount: 20,
    reviews: 226,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 127,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 666,
    discount: 15,
    reviews: 338,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Indirect sunlight, moist soil.",
    height: "10 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 128,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 753,
    discount: 10,
    reviews: 483,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "15 inches",
    weight: "1kg",
    size: "Large"
  },
  {
    id: 129,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 101,
    discount: 15,
    reviews: 118,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 130,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 703,
    discount: 0,
    reviews: 301,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Indirect sunlight, moist soil.",
    height: "15 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 131,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 685,
    discount: 10,
    reviews: 406,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water weekly, indirect sunlight.",
    height: "15 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 132,
    name: "Neem",
    subName: "Azadirachta indica",
    description: "Neem is a popular wooden plant ideal for home and garden decor.",
    price: 233,
    discount: 10,
    reviews: 288,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "wooden",
    careInfo: "Water once a week, keep in sunlight.",
    height: "8 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 133,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 824,
    discount: 0,
    reviews: 466,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "8 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 134,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 443,
    discount: 20,
    reviews: 113,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "10 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 135,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 94,
    discount: 20,
    reviews: 363,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "20 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 136,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 347,
    discount: 0,
    reviews: 219,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Moist soil, low light.",
    height: "8 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 137,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 945,
    discount: 10,
    reviews: 367,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "12 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 138,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 711,
    discount: 5,
    reviews: 83,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Moist soil, low light.",
    height: "12 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 139,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 903,
    discount: 5,
    reviews: 246,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "12 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 140,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 396,
    discount: 5,
    reviews: 236,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Indirect sunlight, moist soil.",
    height: "20 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 141,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 245,
    discount: 15,
    reviews: 155,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "10 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 142,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 861,
    discount: 10,
    reviews: 203,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 143,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 619,
    discount: 20,
    reviews: 99,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Moist soil, low light.",
    height: "20 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 144,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 222,
    discount: 20,
    reviews: 333,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water once a week, keep in sunlight.",
    height: "10 inches",
    weight: "300g",
    size: "Small"
  },
  {
    id: 145,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 563,
    discount: 0,
    reviews: 87,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Indirect sunlight, moist soil.",
    height: "12 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 146,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 716,
    discount: 20,
    reviews: 324,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Moist soil, low light.",
    height: "20 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 147,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 933,
    discount: 0,
    reviews: 66,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 148,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 497,
    discount: 0,
    reviews: 304,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "20 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 149,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 319,
    discount: 5,
    reviews: 185,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 150,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 941,
    discount: 15,
    reviews: 473,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "8 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 151,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 435,
    discount: 10,
    reviews: 237,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Indirect sunlight, moist soil.",
    height: "10 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 152,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 248,
    discount: 20,
    reviews: 152,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 153,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 173,
    discount: 10,
    reviews: 113,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "8 inches",
    weight: "750g",
    size: "Small"
  },
  {
    id: 154,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 705,
    discount: 10,
    reviews: 434,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Moist soil, low light.",
    height: "20 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 155,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 754,
    discount: 10,
    reviews: 97,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Moist soil, low light.",
    height: "10 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 156,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 467,
    discount: 20,
    reviews: 154,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Moist soil, low light.",
    height: "15 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 157,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 844,
    discount: 20,
    reviews: 59,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 158,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 434,
    discount: 15,
    reviews: 110,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Moist soil, low light.",
    height: "8 inches",
    weight: "500g",
    size: "Large"
  },
  {
    id: 159,
    name: "Neem",
    subName: "Azadirachta indica",
    description: "Neem is a popular wooden plant ideal for home and garden decor.",
    price: 240,
    discount: 0,
    reviews: 480,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "wooden",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 160,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 656,
    discount: 0,
    reviews: 283,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Moist soil, low light.",
    height: "20 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 161,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 156,
    discount: 10,
    reviews: 371,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 162,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 733,
    discount: 0,
    reviews: 169,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "flowering",
    careInfo: "Indirect sunlight, moist soil.",
    height: "15 inches",
    weight: "750g",
    size: "Small"
  },
  {
    id: 163,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 388,
    discount: 10,
    reviews: 153,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Moist soil, low light.",
    height: "15 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 164,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 613,
    discount: 20,
    reviews: 191,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water once a week, keep in sunlight.",
    height: "10 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 165,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 544,
    discount: 0,
    reviews: 264,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Full sunlight, moderate watering.",
    height: "8 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 166,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 338,
    discount: 20,
    reviews: 179,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "20 inches",
    weight: "300g",
    size: "Small"
  },
  {
    id: 167,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 681,
    discount: 5,
    reviews: 383,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "indoor",
    careInfo: "Moist soil, low light.",
    height: "15 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 168,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 304,
    discount: 5,
    reviews: 195,
    imageUrl: "https://images.pexels.com/photos/4503263/pexels-photo-4503263.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "20 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 169,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 348,
    discount: 15,
    reviews: 172,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 170,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 426,
    discount: 5,
    reviews: 324,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 171,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 763,
    discount: 15,
    reviews: 75,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 172,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 805,
    discount: 0,
    reviews: 304,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water weekly, indirect sunlight.",
    height: "12 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 173,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 968,
    discount: 15,
    reviews: 363,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "1kg",
    size: "Large"
  },
  {
    id: 174,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 633,
    discount: 15,
    reviews: 149,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Water once a week, keep in sunlight.",
    height: "10 inches",
    weight: "750g",
    size: "Small"
  },
  {
    id: 175,
    name: "Neem",
    subName: "Azadirachta indica",
    description: "Neem is a popular wooden plant ideal for home and garden decor.",
    price: 195,
    discount: 20,
    reviews: 227,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "wooden",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 176,
    name: "Bougainvillea",
    subName: "Color Burst",
    description: "Bougainvillea is a popular outdoor plant ideal for home and garden decor.",
    price: 786,
    discount: 0,
    reviews: 285,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "outdoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "20 inches",
    weight: "300g",
    size: "Small"
  },
  {
    id: 177,
    name: "Neem",
    subName: "Azadirachta indica",
    description: "Neem is a popular wooden plant ideal for home and garden decor.",
    price: 558,
    discount: 0,
    reviews: 397,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "wooden",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "1kg",
    size: "Small"
  },
  {
    id: 178,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 430,
    discount: 10,
    reviews: 350,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Full sunlight, moderate watering.",
    height: "10 inches",
    weight: "1kg",
    size: "Large"
  },
  {
    id: 179,
    name: "Money Plant",
    subName: "Pothos",
    description: "Money Plant is a popular indoor plant ideal for home and garden decor.",
    price: 919,
    discount: 15,
    reviews: 70,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Indirect sunlight, moist soil.",
    height: "20 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 180,
    name: "Neem",
    subName: "Azadirachta indica",
    description: "Neem is a popular wooden plant ideal for home and garden decor.",
    price: 996,
    discount: 10,
    reviews: 397,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "wooden",
    careInfo: "Moist soil, low light.",
    height: "8 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 181,
    name: "Money Plant",
    subName: "Pothos",
    description: "Money Plant is a popular indoor plant ideal for home and garden decor.",
    price: 698,
    discount: 20,
    reviews: 296,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 182,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 974,
    discount: 15,
    reviews: 353,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Moist soil, low light.",
    height: "10 inches",
    weight: "750g",
    size: "Medium"
  },
  {
    id: 183,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 690,
    discount: 20,
    reviews: 463,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Indirect sunlight, moist soil.",
    height: "12 inches",
    weight: "750g",
    size: "Small"
  },
  {
    id: 184,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 147,
    discount: 0,
    reviews: 201,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 185,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 284,
    discount: 20,
    reviews: 100,
    imageUrl: "https://images.pexels.com/photos/3076899/pexels-photo-3076899.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water once a week, keep in sunlight.",
    height: "8 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 186,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 346,
    discount: 10,
    reviews: 134,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Full sunlight, moderate watering.",
    height: "15 inches",
    weight: "750g",
    size: "Large"
  },
  {
    id: 187,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 90,
    discount: 0,
    reviews: 247,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "indoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "12 inches",
    weight: "1kg",
    size: "Large"
  },
  {
    id: 188,
    name: "Snake Plant",
    subName: "Mother-in-law's tongue",
    description: "Snake Plant is a popular indoor plant ideal for home and garden decor.",
    price: 278,
    discount: 0,
    reviews: 291,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "8 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 189,
    name: "Orchid",
    subName: "Phalaenopsis",
    description: "Orchid is a popular flowering plant ideal for home and garden decor.",
    price: 144,
    discount: 5,
    reviews: 179,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 190,
    name: "Money Plant",
    subName: "Pothos",
    description: "Money Plant is a popular indoor plant ideal for home and garden decor.",
    price: 389,
    discount: 20,
    reviews: 489,
    imageUrl: "https://images.pexels.com/photos/57927/rose-flower-blossom-bloom-57927.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water once a week, keep in sunlight.",
    height: "10 inches",
    weight: "500g",
    size: "Medium"
  },
  {
    id: 191,
    name: "Neem",
    subName: "Azadirachta indica",
    description: "Neem is a popular wooden plant ideal for home and garden decor.",
    price: 972,
    discount: 5,
    reviews: 398,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "wooden",
    careInfo: "Indirect sunlight, moist soil.",
    height: "8 inches",
    weight: "1kg",
    size: "Medium"
  },
  {
    id: 192,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 565,
    discount: 10,
    reviews: 311,
    imageUrl: "https://images.pexels.com/photos/6582026/pexels-photo-6582026.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Moist soil, low light.",
    height: "10 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 193,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 377,
    discount: 20,
    reviews: 229,
    imageUrl: "https://images.pexels.com/photos/4503264/pexels-photo-4503264.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Water weekly, indirect sunlight.",
    height: "10 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 194,
    name: "Money Plant",
    subName: "Pothos",
    description: "Money Plant is a popular indoor plant ideal for home and garden decor.",
    price: 341,
    discount: 15,
    reviews: 78,
    imageUrl: "https://images.pexels.com/photos/731905/pexels-photo-731905.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "10 inches",
    weight: "300g",
    size: "Large"
  },
  {
    id: 195,
    name: "Rose",
    subName: "Red Hybrid",
    description: "Rose is a popular flowering plant ideal for home and garden decor.",
    price: 489,
    discount: 0,
    reviews: 215,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "flowering",
    careInfo: "Water once a week, keep in sunlight.",
    height: "12 inches",
    weight: "1kg",
    size: "Large"
  },
  {
    id: 196,
    name: "Money Plant",
    subName: "Pothos",
    description: "Money Plant is a popular indoor plant ideal for home and garden decor.",
    price: 450,
    discount: 0,
    reviews: 252,
    imageUrl: "https://images.pexels.com/photos/12357154/pexels-photo-12357154.jpeg",
    coverImages: [],
    category: "indoor",
    careInfo: "Full sunlight, moderate watering.",
    height: "10 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 197,
    name: "Jade Plant",
    subName: "Lucky Plant",
    description: "Jade Plant is a popular succulent plant ideal for home and garden decor.",
    price: 996,
    discount: 10,
    reviews: 396,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Indirect sunlight, moist soil.",
    height: "12 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 198,
    name: "Aloe Vera",
    subName: "Medicinal Plant",
    description: "Aloe Vera is a popular succulent plant ideal for home and garden decor.",
    price: 696,
    discount: 5,
    reviews: 148,
    imageUrl: "https://images.pexels.com/photos/1003834/pexels-photo-1003834.jpeg",
    coverImages: [],
    category: "succulent",
    careInfo: "Full sunlight, moderate watering.",
    height: "8 inches",
    weight: "300g",
    size: "Medium"
  },
  {
    id: 199,
    name: "Bonsai Ficus",
    subName: "Mini Tree",
    description: "Bonsai Ficus is a popular bonsai plant ideal for home and garden decor.",
    price: 83,
    discount: 0,
    reviews: 375,
    imageUrl: "https://images.pexels.com/photos/5699661/pexels-photo-5699661.jpeg",
    coverImages: [],
    category: "bonsai",
    careInfo: "Water once a week, keep in sunlight.",
    height: "8 inches",
    weight: "500g",
    size: "Small"
  },
  {
    id: 200,
    name: "Peace Lily",
    subName: "Spathiphyllum",
    description: "Peace Lily is a popular indoor plant ideal for home and garden decor.",
    price: 705,
    discount: 0,
    reviews: 247,
    imageUrl: "https://images.pexels.com/photos/6729/rose-red-love-gift.jpg",
    coverImages: [],
    category: "indoor",
    careInfo: "Water weekly, indirect sunlight.",
    height: "12 inches",
    weight: "750g",
    size: "Medium"
  },
];
