import { Plant } from '@/types';

export const plantsData: Plant[] = [
  {
    id: 101,
    name: 'Hybiscus Red',
    tamilName: 'செம்பருத்தி',
    subName: 'Red Hibiscus',
    description:
      'A vibrant flowering plant commonly found in Tamil homes, ideal for gardens and rituals.',
    baseImageUrl: '/plants/thumbnail/semparuthi.jpg',
    category: 'flowering',
    careInfo: 'Needs full sun, well-drained soil, and regular watering. Avoid overwatering.',
    fertilizingInfo:
      'Use organic compost or a balanced NPK fertilizer every 15 days during blooming season.',
    usageInfo:
      'Commonly used in pooja rituals, garden decor, and traditional medicine (Siddha and Ayurveda).',
    isAvailable: true,
    isFeatured: true,
    tags: ['ritual use', 'fast grower', 'red flower', 'Tamil Nadu'],
    relatedPlantsIds: [],
    variants: [
      {
        id: '101-4x6',
        size: '4 x 6',
        price: 15,
        discount: 19,
        ratings: 4.5,
        reviewsCount: 134,
        growthRate: 'fast',
        height: '2.5 feet',
        weight: '0.5kg',
        quantityInStock: 800,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/semparuthi-1.jpg',
          '/plants/cover_images/semparuthi-2.jpg',
        ],
      },
      {
        id: '101-7x8',
        size: '7 x 8',
        price: 65,
        discount: 19,
        ratings: 4.5,
        reviewsCount: 134,
        growthRate: 'fast',
        height: '2.5 feet',
        weight: '1.2kg',
        quantityInStock: 38,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/semparuthi-1.jpg',
          '/plants/cover_images/semparuthi-2.jpg',
          '/plants/cover_images/semparuthi-3.jpg',
        ],
      },
    ],
  },
  {
    id: 102,
    name: 'Ixora White',
    tamilName: 'இட்லிப் பூ',
    subName: 'White Jungle Flame',
    description:
      'A sacred and elegant flowering plant known for its clusters of white blooms, often used in rituals and as an ornamental hedge.',
    baseImageUrl: '/plants/thumbnail/ixora_white.jpg',
    category: 'flowering',
    careInfo:
      'Prefers partial to full sunlight, well-drained acidic soil, and moderate watering. Prune to encourage bushy growth.',
    fertilizingInfo:
      'Fertilize monthly with a phosphorous-rich flowering plant feed during growing season.',
    usageInfo:
      'Commonly planted along borders, used in poojas and ceremonies, and appreciated for its calm and serene look.',
    isAvailable: true,
    isFeatured: true,
    tags: ['white flower', 'hedge', 'ritual use', 'low maintenance'],
    relatedPlantsIds: [103],
    variants: [
      {
        id: '102-4x6',
        size: '4 x 6',
        price: 15,
        discount: 16,
        ratings: 4.3,
        reviewsCount: 189,
        growthRate: 'medium',
        height: '1.0 feet',
        weight: '0.5 kg',
        quantityInStock: 4200,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_white-1.jpg',
          '/plants/cover_images/ixora_white-2.jpg',
        ],
      },
      {
        id: '102-7x8',
        size: '7 x 8',
        price: 45,
        discount: 36,
        ratings: 4.3,
        reviewsCount: 89,
        growthRate: 'medium',
        height: '1.8 feet',
        weight: '1.2 kg',
        quantityInStock: 42,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_white-1.jpg',
          '/plants/cover_images/ixora_white-2.jpg',
        ],
      },
      {
        id: '102-10x12',
        size: '10 x 12',
        price: 145,
        discount: 56,
        ratings: 4.9,
        reviewsCount: 89,
        growthRate: 'medium',
        height: '2.0 feet',
        weight: '1.5 kg',
        quantityInStock: 12,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_white-1.jpg',
          '/plants/cover_images/ixora_white-2.jpg',
        ],
      },
    ],
  },
  {
    id: 103,
    name: 'Ixora Pink',
    tamilName: 'ரோஜா இட்லிப் பூ',
    subName: 'Pink Jungle Flame',
    description:
      'A vibrant flowering plant admired for its lush clusters of pink blooms, ideal for gardens and spiritual offerings.',
    baseImageUrl: '/plants/thumbnail/ixora_pink.jpg',
    category: 'flowering',
    careInfo:
      'Thrives in partial to full sunlight with well-draining acidic soil. Water moderately and prune for fuller growth.',
    fertilizingInfo: 'Use a bloom-boosting fertilizer once a month during active growth.',
    usageInfo:
      'Perfect for borders, spiritual use, and decorative landscaping due to its soft pink charm.',
    isAvailable: true,
    isFeatured: true,
    tags: ['pink flower', 'ornamental', 'hedge', 'low maintenance'],
    relatedPlantsIds: [102],
    variants: [
      {
        id: '103-7x8',
        size: '7 x 8',
        price: 50,
        discount: 40,
        ratings: 4.4,
        reviewsCount: 77,
        growthRate: 'medium',
        height: '1.3 feet',
        weight: '1.1 kg',
        quantityInStock: 38,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_pink-1.jpg',
          '/plants/cover_images/ixora_pink-2.jpg',
        ],
      },
       {
        id: '103-4x6',
        size: '4 x 6',
        price: 15,
        discount: 40,
        ratings: 4.6,
        reviewsCount: 77,
        growthRate: 'medium',
        height: '1.0 feet',
        weight: '0.5 kg',
        quantityInStock: 38,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_pink-1.jpg',
          '/plants/cover_images/ixora_pink-2.jpg',
        ],
      },
    ],
  },
  {
    id: 104,
    name: 'Aralia White',
    tamilName: 'வெள்ளை அரலியா',
    subName: 'White Aralia',
    description:
      'An elegant foliage plant with lacy white-edged leaves, prized for its ornamental appeal and air-purifying qualities.',
    baseImageUrl: '/plants/thumbnail/aralia_white.jpg',
    category: 'indoor',
    careInfo:
      'Prefers bright indirect light and thrives in well-draining soil. Water when the top inch of soil is dry.',
    fertilizingInfo:
      'Feed with a balanced houseplant fertilizer every 4–6 weeks during the growing season.',
    usageInfo:
      'Ideal for indoor corners, tabletops, and office spaces due to its calming foliage and compact size.',
    isAvailable: true,
    isFeatured: true,
    tags: ['white aralia', 'foliage', 'indoor plant', 'air purifier'],
    relatedPlantsIds: [],
    variants: [
      {
        id: '104-7x8',
        size: '7 x 8',
        price: 45,
        discount: 32,
        ratings: 4.9,
        reviewsCount: 64,
        growthRate: 'slow',
        height: '1.3 feet',
        weight: '1.1 kg',
        quantityInStock: 29,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/aralia_white-1.jpg',
          '/plants/cover_images/aralia_white-2.jpg',
        ],
      },
      {
        id: '104-4x6',
        size: '4 x 6',
        price: 25,
        discount: 12,
        ratings: 4.2,
        reviewsCount: 64,
        growthRate: 'slow',
        height: '1.0 feet',
        weight: '0.6 kg',
        quantityInStock: 160,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/aralia_white-1.jpg',
          '/plants/cover_images/aralia_white-2.jpg',
        ],
      },
    ],
  },
  {
    id: 105,
    name: 'Hawaiian Ti Plant',
    tamilName: 'ஹவாயின் குட் லக் செடி',
    subName: 'Hawaiian Good Luck Plant',
    description:
      'A vibrant tropical foliage plant known for its colorful, glossy leaves. It is believed to bring good luck and positive energy.',
    baseImageUrl: '/plants/thumbnail/hawaiian_ti.jpg',
    category: 'indoor',
    careInfo:
      'Grows best in bright, filtered light and slightly moist soil. Avoid direct harsh sunlight and cold drafts.',
    fertilizingInfo: 'Apply a balanced liquid fertilizer once a month during active growth.',
    usageInfo:
      'Perfect for indoor décor, entrances, and balconies. Often used in feng shui and spiritual settings.',
    isAvailable: true,
    isFeatured: true,
    tags: ['ti plant', 'good luck', 'tropical foliage', 'indoor plant'],
    relatedPlantsIds: [],
    variants: [
      {
        id: '105-7x8',
        size: '7 x 8',
        price: 75,
        discount: 62,
        ratings: 4.7,
        reviewsCount: 58,
        growthRate: 'medium',
        height: '2.4 feet',
        weight: '1.2 kg',
        quantityInStock: 24,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/hawaiian_ti-1.jpg',
          '/plants/cover_images/hawaiian_ti-2.jpg',
        ],
      },
    ],
  },
];
