import { Plant } from '@/types';

export const plantsData: Plant[] = [
  {
    id: 101,
    name: 'Hybiscus Red',
    tamilName: 'செம்பருத்தி',
    subName: 'Red Hibiscus',
    description:
      'A vibrant flowering plant commonly found in Tamil homes, ideal for gardens and rituals.',
    baseImageUrl: '/plants/thumbnail/semparuthi.jpg',
    category: 'flowering',
    careInfo: 'Needs full sun, well-drained soil, and regular watering. Avoid overwatering.',
    fertilizingInfo:
      'Use organic compost or a balanced NPK fertilizer every 15 days during blooming season.',
    usageInfo:
      'Commonly used in pooja rituals, garden decor, and traditional medicine (Siddha and Ayurveda).',
    isAvailable: true,
    isFeatured: true,
    tags: ['ritual use', 'fast grower', 'red flower', 'Tamil Nadu'],
    relatedPlantsIds: [102, 104],
    variants: [
      {
        id: '101-4x6',
        size: '4 x 6',
        price: 15,
        discount: 19,
        ratings: 4.5,
        reviewsCount: 134,
        growthRate: 'fast',
        height: '2.5 feet',
        weight: '0.5kg',
        quantityInStock: 800,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/semparuthi-1.jpg',
          '/plants/cover_images/semparuthi-2.jpg',
        ],
      },
      {
        id: '101-7x8',
        size: '7 x 8',
        price: 65,
        discount: 19,
        ratings: 4.5,
        reviewsCount: 134,
        growthRate: 'fast',
        height: '2.5 feet',
        weight: '1.2kg',
        quantityInStock: 38,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/semparuthi-1.jpg',
          '/plants/cover_images/semparuthi-2.jpg',
          '/plants/cover_images/semparuthi-3.jpg',
        ],
      },
    ],
  },
  {
    id: 102,
    name: 'Ixora White',
    tamilName: 'இட்லிப் பூ',
    subName: 'White Jungle Flame',
    description:
      'A sacred and elegant flowering plant known for its clusters of white blooms, often used in rituals and as an ornamental hedge.',
    baseImageUrl: '/plants/thumbnail/ixora_white.jpg',
    category: 'flowering',
    careInfo:
      'Prefers partial to full sunlight, well-drained acidic soil, and moderate watering. Prune to encourage bushy growth.',
    fertilizingInfo:
      'Fertilize monthly with a phosphorous-rich flowering plant feed during growing season.',
    usageInfo:
      'Commonly planted along borders, used in poojas and ceremonies, and appreciated for its calm and serene look.',
    isAvailable: true,
    isFeatured: false,
    tags: ['white flower', 'hedge', 'ritual use', 'low maintenance'],
    relatedPlantsIds: [103],
    variants: [
      {
        id: '102-4x6',
        size: '4 x 6',
        price: 15,
        discount: 16,
        ratings: 4.3,
        reviewsCount: 189,
        growthRate: 'medium',
        height: '1.0 feet',
        weight: '0.5 kg',
        quantityInStock: 4200,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_white-1.jpg',
          '/plants/cover_images/ixora_white-2.jpg',
        ],
      },
      {
        id: '102-7x8',
        size: '7 x 8',
        price: 45,
        discount: 36,
        ratings: 4.3,
        reviewsCount: 89,
        growthRate: 'medium',
        height: '1.8 feet',
        weight: '1.2 kg',
        quantityInStock: 42,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_white-1.jpg',
          '/plants/cover_images/ixora_white-2.jpg',
        ],
      },
      {
        id: '102-10x12',
        size: '10 x 12',
        price: 145,
        discount: 56,
        ratings: 4.9,
        reviewsCount: 89,
        growthRate: 'medium',
        height: '2.0 feet',
        weight: '1.5 kg',
        quantityInStock: 12,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_white-1.jpg',
          '/plants/cover_images/ixora_white-2.jpg',
        ],
      },
    ],
  },
  {
    id: 103,
    name: 'Ixora Pink',
    tamilName: 'ரோஜா இட்லிப் பூ',
    subName: 'Pink Jungle Flame',
    description:
      'A vibrant flowering plant admired for its lush clusters of pink blooms, ideal for gardens and spiritual offerings.',
    baseImageUrl: '/plants/thumbnail/ixora_pink.jpg',
    category: 'flowering',
    careInfo:
      'Thrives in partial to full sunlight with well-draining acidic soil. Water moderately and prune for fuller growth.',
    fertilizingInfo: 'Use a bloom-boosting fertilizer once a month during active growth.',
    usageInfo:
      'Perfect for borders, spiritual use, and decorative landscaping due to its soft pink charm.',
    isAvailable: true,
    isFeatured: false,
    tags: ['pink flower', 'ornamental', 'hedge', 'low maintenance'],
    relatedPlantsIds: [102, 101],
    variants: [
      {
        id: '103-7x8',
        size: '7 x 8',
        price: 50,
        discount: 40,
        ratings: 4.4,
        reviewsCount: 77,
        growthRate: 'medium',
        height: '1.3 feet',
        weight: '1.1 kg',
        quantityInStock: 38,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_pink-1.jpg',
          '/plants/cover_images/ixora_pink-2.jpg',
        ],
      },
      {
        id: '103-4x6',
        size: '4 x 6',
        price: 15,
        discount: 40,
        ratings: 4.6,
        reviewsCount: 77,
        growthRate: 'medium',
        height: '1.0 feet',
        weight: '0.5 kg',
        quantityInStock: 38,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_pink-1.jpg',
          '/plants/cover_images/ixora_pink-2.jpg',
        ],
      },
    ],
  },
  {
    id: 104,
    name: 'Aralia White',
    tamilName: 'வெள்ளை அரலியா',
    subName: 'White Aralia',
    description:
      'An elegant foliage plant with lacy white-edged leaves, prized for its ornamental appeal and air-purifying qualities.',
    baseImageUrl: '/plants/thumbnail/aralia_white.jpg',
    category: 'indoor',
    careInfo:
      'Prefers bright indirect light and thrives in well-draining soil. Water when the top inch of soil is dry.',
    fertilizingInfo:
      'Feed with a balanced houseplant fertilizer every 4–6 weeks during the growing season.',
    usageInfo:
      'Ideal for indoor corners, tabletops, and office spaces due to its calming foliage and compact size.',
    isAvailable: true,
    isFeatured: true,
    tags: ['white aralia', 'foliage', 'indoor plant', 'air purifier'],
    relatedPlantsIds: [105],
    variants: [
      {
        id: '104-7x8',
        size: '7 x 8',
        price: 45,
        discount: 32,
        ratings: 4.9,
        reviewsCount: 64,
        growthRate: 'slow',
        height: '1.3 feet',
        weight: '1.1 kg',
        quantityInStock: 29,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/aralia_white-1.jpg',
          '/plants/cover_images/aralia_white-2.jpg',
        ],
      },
      {
        id: '104-4x6',
        size: '4 x 6',
        price: 25,
        discount: 12,
        ratings: 4.2,
        reviewsCount: 64,
        growthRate: 'slow',
        height: '1.0 feet',
        weight: '0.6 kg',
        quantityInStock: 160,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/aralia_white-1.jpg',
          '/plants/cover_images/aralia_white-2.jpg',
        ],
      },
    ],
  },
  {
    id: 105,
    name: 'Hawaiian Ti Plant',
    tamilName: 'ஹவாயின் குட் லக் செடி',
    subName: 'Hawaiian Good Luck Plant',
    description:
      'A vibrant tropical foliage plant known for its colorful, glossy leaves. It is believed to bring good luck and positive energy.',
    baseImageUrl: '/plants/thumbnail/hawaiian_ti.jpg',
    category: 'indoor',
    careInfo:
      'Grows best in bright, filtered light and slightly moist soil. Avoid direct harsh sunlight and cold drafts.',
    fertilizingInfo: 'Apply a balanced liquid fertilizer once a month during active growth.',
    usageInfo:
      'Perfect for indoor décor, entrances, and balconies. Often used in feng shui and spiritual settings.',
    isAvailable: true,
    isFeatured: true,
    tags: ['ti plant', 'good luck', 'tropical foliage', 'indoor plant'],
    relatedPlantsIds: [104],
    variants: [
      {
        id: '105-7x8',
        size: '7 x 8',
        price: 75,
        discount: 62,
        ratings: 4.7,
        reviewsCount: 58,
        growthRate: 'medium',
        height: '2.4 feet',
        weight: '1.2 kg',
        quantityInStock: 24,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/hawaiian_ti-1.jpg',
          '/plants/cover_images/hawaiian_ti-2.jpg',
        ],
      },
    ],
  },
  {
    id: 106,
    name: 'Pannir Rose Plant',
    tamilName: 'பன்னீர் ரோஜா செடி',
    subName: 'Fragrant Pannir Rose',
    description:
      'A beautiful and fragrant variety of rose native to South India. Known for its soft pink petals and strong, sweet scent.',
    baseImageUrl: '/plants/thumbnail/pannir_rose.jpg',
    category: 'flowering',
    careInfo:
      'Thrives in full sun with well-drained soil. Requires regular watering and pruning for continuous blooming.',
    fertilizingInfo: 'Feed with organic rose fertilizer once every 2-3 weeks during the growing season.',
    usageInfo:
      'Widely used in religious rituals, garlands, perfumes, and for its ornamental beauty in home gardens.',
    isAvailable: true,
    isFeatured: true,
    tags: ['rose', 'pannir rose', 'fragrant flower', 'outdoor plant'],
    relatedPlantsIds: [103],
    variants: [
      {
        id: '106-7x8',
        size: '7 x 8',
        price: 80,
        discount: 25,
        ratings: 5.0,
        reviewsCount: 45,
        growthRate: 'fast',
        height: '1.8 feet',
        weight: '1 kg',
        quantityInStock: 30,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/pannir_rose-1.jpg',
          '/plants/cover_images/pannir_rose-2.jpg',
        ],
      },
      {
        id: '106-4x6',
        size: '4 x 6',
        price: 15,
        discount: 15,
        ratings: 4.0,
        reviewsCount: 30,
        growthRate: 'fast',
        height: '1.0 feet',
        weight: '0.5 kg',
        quantityInStock: 1020,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/pannir_rose-1.jpg',
          '/plants/cover_images/pannir_rose-2.jpg',
        ],
      },
    ],
  },
  {
    id: 107,
    name: 'Ixora Red Plant',
    tamilName: 'இட்லி பூ செடி (சிகப்பு)',
    subName: 'Red Ixora Flowering Shrub',
    description:
      'A dense, bushy flowering plant known for its bright red clusters of flowers. Popular in tropical gardens and temples.',
    baseImageUrl: '/plants/thumbnail/ixora_red.jpg',
    category: 'flowering',
    careInfo:
      'Prefers full sun to partial shade. Needs well-drained acidic soil and regular watering. Prune to maintain shape.',
    fertilizingInfo: 'Use a phosphorus-rich fertilizer once a month to promote flowering.',
    usageInfo:
      'Ideal for hedges, garden borders, and temple offerings. Attracts butterflies and adds vibrant color to landscapes.',
    isAvailable: true,
    isFeatured: false,
    tags: ['ixora', 'idly poo', 'red flower', 'hedge plant', 'outdoor plant'],
    relatedPlantsIds: [103, 104, 102],
    variants: [
      {
        id: '107-4x6',
        size: '4 x 6',
        price: 15,
        discount: 50,
        ratings: 4.5,
        reviewsCount: 37,
        growthRate: 'medium',
        height: '1.2 feet',
        weight: '0.6 kg',
        quantityInStock: 1500,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_red-1.jpg',
          '/plants/cover_images/ixora_red-2.jpg',
        ],
      },
      {
        id: '107-7x8',
        size: '7 x 8',
        price: 45,
        discount: 20,
        ratings: 4.5,
        reviewsCount: 107,
        growthRate: 'medium',
        height: '1.6 feet',
        weight: '1.3 kg',
        quantityInStock: 200,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/ixora_red-1.jpg',
          '/plants/cover_images/ixora_red-2.jpg',
        ],
      },
    ],
  },
  {
    id: 108,
    name: 'Yellow Allamanda Plant',
    tamilName: 'மஞ்சள் அலமாண்டா செடி',
    subName: 'Golden Trumpet Vine',
    description:
      'A fast-growing ornamental vine known for its bright yellow trumpet-shaped flowers. Often used to decorate fences and garden walls.',
    baseImageUrl: '/plants/thumbnail/yellow_allamanda.jpg',
    category: 'flowering',
    careInfo:
      'Thrives in full sun with regular watering and well-drained soil. Requires support for climbing and occasional pruning to control size.',
    fertilizingInfo: 'Feed with a balanced fertilizer every 2–3 weeks during blooming season.',
    usageInfo:
      'Perfect for fences, trellises, balconies, and decorative garden walls. Adds a tropical vibe and attracts pollinators.',
    isAvailable: true,
    isFeatured: true,
    tags: ['allamanda', 'yellow flower', 'golden trumpet', 'climber', 'outdoor plant'],
    relatedPlantsIds: [107, 101],
    variants: [
      {
        id: '108-4x6',
        size: '4 x 6',
        price: 20,
        discount: 41,
        ratings: 4.4,
        reviewsCount: 29,
        growthRate: 'fast',
        height: '2.0 feet',
        weight: '0.6 kg',
        quantityInStock: 1135,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/yellow_allamanda-1.jpg',
          '/plants/cover_images/yellow_allamanda-2.jpg',
        ],
      },
      {
        id: '108-7x8',
        size: '7 x 8',
        price: 60,
        discount: 32,
        ratings: 4.6,
        reviewsCount: 129,
        growthRate: 'fast',
        height: '3.2 feet',
        weight: '1.4 kg',
        quantityInStock: 120,
        isAvailable: true,
        coverImages: [
          '/plants/cover_images/yellow_allamanda-1.jpg',
          '/plants/cover_images/yellow_allamanda-2.jpg',
        ],
      },
    ],
  },
  {
    id: 109,
    name: 'Guava Plant',
    tamilName: 'கொய்யா செடி',
    subName: 'Psidium guajava',
    description:
      'A tropical fruit plant known for its sweet and nutritious guava fruits. Commonly grown in home gardens and farms.',
    baseImageUrl: '/plants/thumbnail/guava.jpg',
    category: 'fruiting',
    careInfo:
      'Prefers full sunlight and moderate watering. Grows well in loamy soil. Prune to shape and remove dead branches regularly.',
    fertilizingInfo: 'Apply organic compost or fruit plant fertilizer once a month.',
    usageInfo:
      'Ideal for home gardens, kitchen gardens, and small orchards. Produces edible fruit rich in Vitamin C.',
    isAvailable: true,
    isFeatured: true,
    tags: ['guava', 'fruit plant', 'psidium', 'home garden'],
    relatedPlantsIds: [108, 101],
    variants: [
      {
        id: '109-4x6',
        size: '4 x 6',
        price: 18,
        discount: 35,
        ratings: 4.3,
        reviewsCount: 42,
        growthRate: 'medium',
        height: '1.5 feet',
        weight: '0.8 kg',
        quantityInStock: 920,
        isAvailable: true,
        coverImages: ['/plants/cover_images/guava-1.jpg', '/plants/cover_images/guava-2.jpg'],
      },
      {
        id: '109-7x8',
        size: '7 x 8',
        price: 55,
        discount: 28,
        ratings: 4.5,
        reviewsCount: 88,
        growthRate: 'medium',
        height: '2.5 feet',
        weight: '1.2 kg',
        quantityInStock: 260,
        isAvailable: true,
        coverImages: ['/plants/cover_images/guava-1.jpg', '/plants/cover_images/guava-2.jpg'],
      },
      {
        id: '109-7x10',
        size: '7 x 10',
        price: 85,
        discount: 22,
        ratings: 4.6,
        reviewsCount: 150,
        growthRate: 'medium',
        height: '3.5 feet',
        weight: '2.1 kg',
        quantityInStock: 95,
        isAvailable: true,
        coverImages: ['/plants/cover_images/guava-1.jpg', '/plants/cover_images/guava-2.jpg'],
      },
    ],
  },
  {
    id: 110,
    name: 'Golden Shower Tree',
    tamilName: 'சர்க்கொன்றை மரம்',
    subName: 'Cassia fistula',
    description:
      'A majestic flowering tree known for its cascading yellow blooms. National tree of Thailand and widely loved in Tamil culture.',
    baseImageUrl: '/plants/thumbnail/golden_shower.jpg',
    category: 'flowering',
    careInfo:
      'Needs full sunlight and occasional deep watering. Grows best in well-drained sandy or loamy soil.',
    fertilizingInfo: 'Use slow-release fertilizer twice during growing season.',
    usageInfo:
      'Perfect for avenue planting, parks, and large gardens. Its vibrant blooms add elegance and cultural significance.',
    isAvailable: true,
    isFeatured: true,
    tags: ['cassia', 'golden tree', 'flowering tree', 'kanikkonnai'],
    relatedPlantsIds: [108, 109],
    variants: [
      {
        id: '110-4x6',
        size: '4 x 6',
        price: 20,
        discount: 40,
        ratings: 4.2,
        reviewsCount: 34,
        growthRate: 'fast',
        height: '1.2 feet',
        weight: '0.6 kg',
        quantityInStock: 700,
        isAvailable: true,
        coverImages: ['/plants/cover_images/golden_shower-1.jpg', '/plants/cover_images/golden_shower-2.jpg'],
      },
      {
        id: '110-7x8',
        size: '7 x 8',
        price: 60,
        discount: 25,
        ratings: 4.5,
        reviewsCount: 74,
        growthRate: 'fast',
        height: '2.8 feet',
        weight: '1.6 kg',
        quantityInStock: 165,
        isAvailable: true,
        coverImages: ['/plants/cover_images/golden_shower-1.jpg', '/plants/cover_images/golden_shower-2.jpg'],
      },
      {
        id: '110-7x10',
        size: '7 x 10',
        price: 90,
        discount: 18,
        ratings: 4.7,
        reviewsCount: 201,
        growthRate: 'fast',
        height: '3.6 feet',
        weight: '2.3 kg',
        quantityInStock: 80,
        isAvailable: true,
        coverImages: ['/plants/cover_images/golden_shower-1.jpg', '/plants/cover_images/golden_shower-2.jpg'],
      },
    ],
  },
  {
    id: 111,
    name: 'Wild Fig Tree',
    tamilName: 'காட்டு அத்தி மரம்',
    subName: 'Ficus racemosa',
    description:
      'A sacred and medicinal tree native to South Asia. Produces small edible figs and supports diverse wildlife.',
    baseImageUrl: '/plants/thumbnail/wild_fig.jpg',
    category: 'fruiting',
    careInfo:
      'Grows in full to partial sunlight. Requires minimal care once established and prefers moist, well-drained soil.',
    fertilizingInfo: 'Use organic compost every 2 months during active growth.',
    usageInfo:
      'Used in Ayurveda and traditional medicine. Suitable for large gardens, temple grounds, and spiritual landscapes.',
    isAvailable: true,
    isFeatured: true,
    tags: ['fig', 'ficus', 'medicinal plant', 'sacred tree'],
    relatedPlantsIds: [110, 101],
    variants: [
      {
        id: '111-4x6',
        size: '4 x 6',
        price: 15,
        discount: 30,
        ratings: 4.0,
        reviewsCount: 21,
        growthRate: 'slow',
        height: '1.3 feet',
        weight: '0.9 kg',
        quantityInStock: 600,
        isAvailable: true,
        coverImages: ['/plants/cover_images/wild_fig-1.jpg', '/plants/cover_images/wild_fig-2.jpg'],
      },
      {
        id: '111-7x8',
        size: '7 x 8',
        price: 50,
        discount: 27,
        ratings: 4.3,
        reviewsCount: 56,
        growthRate: 'slow',
        height: '2.1 feet',
        weight: '1.5 kg',
        quantityInStock: 140,
        isAvailable: true,
        coverImages: ['/plants/cover_images/wild_fig-1.jpg', '/plants/cover_images/wild_fig-2.jpg'],
      },
      {
        id: '111-7x10',
        size: '7 x 10',
        price: 82,
        discount: 20,
        ratings: 4.5,
        reviewsCount: 120,
        growthRate: 'slow',
        height: '3.2 feet',
        weight: '2.4 kg',
        quantityInStock: 70,
        isAvailable: true,
        coverImages: ['/plants/cover_images/wild_fig-1.jpg', '/plants/cover_images/wild_fig-2.jpg'],
      },
    ],
  }

];
